apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: image
spec:
  version: {{ .TagName }}
  homepage: https://github.com/pete911/kubectl-image
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      {{addURIAndSha "https://github.com/pete911/kubectl-image/releases/download/${tag}/kubectl-image_${version}_darwin_amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-image
      files:
        - from: kubectl-image
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      {{addURIAndSha "https://github.com/pete911/kubectl-image/releases/download/${tag}/kubectl-image_${version}_darwin_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-image
      files:
        - from: kubectl-image
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      {{addURIAndSha "https://github.com/pete911/kubectl-image/releases/download/${tag}/kubectl-image_${version}_linux_amd64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-image
      files:
        - from: kubectl-image
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      {{addURIAndSha "https://github.com/pete911/kubectl-image/releases/download/${tag}/kubectl-image_${version}_linux_arm64.tar.gz" .TagName | indent 6 }}
      bin: kubectl-image
      files:
        - from: kubectl-image
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      {{addURIAndSha "https://github.com/pete911/kubectl-image/releases/download/${tag}/kubectl-image_${version}_windows_amd64.zip" .TagName | indent 6 }}
      bin: kubectl-image.exe
      files:
        - from: kubectl-image.exe
          to: .
        - from: LICENSE
          to: .
    - selector:
        matchLabels:
          os: windows
          arch: arm64
      {{addURIAndSha "https://github.com/pete911/kubectl-image/releases/download/${tag}/kubectl-image_${version}_windows_arm64.zip" .TagName | indent 6 }}
      bin: kubectl-image.exe
      files:
        - from: kubectl-image.exe
          to: .
        - from: LICENSE
          to: .
  shortDescription: Query container images by namespace/cluster
  description: |
    kubectl image is a subcommand to query images in the Kubernetes cluster, their size, id and tag. Output also
    displays the number of pods (running, failed and restarted) per image.
